# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Lila-Joyce Jomok
description:     'Adventures in Data Science'
url:              https://lilajomok.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Lila Jomok'
  url:            https://twitter.com/rairadraws

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

exclude: ["vendor"]

# Custom vars
#version:            3.4.1
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
#  repo:             https://github.com/fongandrew/hydeout

disqus:
   shortname: lilajomok-blog

google_analytics: UA-108829050-1
