# Site settings
title: Lila Jomok
header-img: img/home-bg.jpg
email: lilajomok@gmail.com
copyright_name: Lila-Joyce Jomok
# description: "Write your site description here. It will be used as your sites meta description as well!"
# baseurl: "/lilajomok.github.io/"
# url: "http://yourdomain.com"
twitter_username: rairaDraws
github_username:  lilajomok
# facebook_username:  StartBootstrap
email_username:  lilajomok@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
