# Dependencies
markdown:                 kramdown
highlighter:              rouge

# CSS Styles
sass:
  # sass_dir: ./assets/css
  # style: compressed

# Setup
title:                    Lila-Joyce Jomok
description:              'Data Analyst | Developer'
copyright:                Lila-Joyce Jomok
permalink:                /blog/:year-:month-:day/:title
#logo_url:                 /images/logo.svg
#favicon:                 something.ico 

# Social Media
linkedin:        lilajomok
twitter:         rairaDraws
# facebook_url:    user 
# instagram:       user
# snapchat:        user
# dribble:         user
gh:              lilajomok
# 500px:           user
# tumblr:          user
# deviantart:      user
# spotify:         user
# youtube_url:     url
# pinterest:       user

# Contact
#phone:                +12345678912
email:               lilajomok@gmail.com  

# Google Analytics
google_analytics_ID:  UA-108829050-1

# Disqus
disqus:
  - shortname: lilajomok-blog